import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  button: {
    position: "absolute",
    bottom: 20,
    alignSelf: "center",
    backgroundColor: "#121212",
    width: 300,
    borderRadius: 50,
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  container: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    textAlign: "center",
    fontSize: 18,
  },
  checkoutButton: {
    backgroundColor: "#121212",
    paddingHorizontal: 20,
    paddingVertical: 15,
    width: 280,
    alignSelf: "center",
    borderRadius: 50,
    marginVertical: 15,
  },
  checkoutButtonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "700",
    textTransform: "capitalize",
    letterSpacing: 3,
    fontSize: 16,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  selectedItemView: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "70%",
    backgroundColor: "#fff",
    borderTopStartRadius: 15,
    borderTopEndRadius: 15,
    paddingTop: 10,
    paddingHorizontal: 5,
  },
  restaurantName: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 10,
  },
  totalPrice: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 10,
    marginVertical: 10,
    padding: 2,
  },
  totalText: {
    fontSize: 18,
    fontWeight: "600",
  },
  loadingAnimationContainer: {
    position: "absolute",
    flex: 1,
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
    backgroundColor: "black",
    opacity: 0.6,
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 1,
  },
});
